// Nexus JEE - Animation Manifest
// Maps concept names and chapter IDs to pre-rendered Manim animation files
// This file is auto-generated by render_all.py but can also be hand-edited

export const ANIMATIONS = {
  // ═══════════════════════════════════════════════════════════
  // PHYSICS
  // ═══════════════════════════════════════════════════════════

  // phy_01 - Units and Measurements
  "basic unit conversion": { file: "/animations/physics/phy_01/dimensional_analysis.webm", title: "Dimensional Analysis" },
  "dimensional analysis": { file: "/animations/physics/phy_01/dimensional_analysis.webm", title: "Dimensional Analysis" },
  "error propagation": { file: "/animations/physics/phy_01/error_propagation.webm", title: "Error Propagation" },

  // phy_02 - Kinematics
  "equations of motion": { file: "/animations/physics/phy_02/equations_of_motion.webm", title: "Equations of Motion" },
  "displacement vs distance": { file: "/animations/physics/phy_02/displacement_time.webm", title: "Displacement-Time Relation" },
  "displacement_time": { file: "/animations/physics/phy_02/displacement_time.webm", title: "Displacement-Time Relation" },
  "velocity_displacement": { file: "/animations/physics/phy_02/velocity_displacement.webm", title: "Velocity-Displacement" },
  "projectile basics": { file: "/animations/physics/phy_02/time_of_flight.webm", title: "Time of Flight" },
  "2D projectile": { file: "/animations/physics/phy_02/horizontal_range.webm", title: "Horizontal Range" },

  // phy_03 - Laws of Motion
  "Newton first law": { file: "/animations/physics/phy_03/newton_second_law.webm", title: "Newton's Second Law" },
  "Newton second law": { file: "/animations/physics/phy_03/newton_second_law.webm", title: "Newton's Second Law" },
  "Newton third law": { file: "/animations/physics/phy_03/newton_second_law.webm", title: "Newton's Second Law" },
  "static friction": { file: "/animations/physics/phy_03/friction.webm", title: "Friction" },
  "kinetic friction": { file: "/animations/physics/phy_03/friction.webm", title: "Friction" },
  "circular motion forces": { file: "/animations/physics/phy_03/centripetal_acceleration.webm", title: "Centripetal Acceleration" },
  "pseudo force basics": { file: "/animations/physics/phy_03/pseudo_force.webm", title: "Pseudo Force" },

  // phy_04 - Work, Energy and Power
  "work by constant force": { file: "/animations/physics/phy_04/work_by_force.webm", title: "Work by Force" },
  "work by variable force": { file: "/animations/physics/phy_04/work_by_force.webm", title: "Work by Force" },
  "kinetic energy": { file: "/animations/physics/phy_04/work_energy_theorem.webm", title: "Work-Energy Theorem" },
  "potential energy": { file: "/animations/physics/phy_04/potential_energy.webm", title: "Potential Energy" },
  "conservation of energy": { file: "/animations/physics/phy_04/potential_energy.webm", title: "Potential Energy" },
  "power": { file: "/animations/physics/phy_04/power.webm", title: "Power" },

  // phy_05 - Rotational Motion
  "basic rotation kinematics": { file: "/animations/physics/phy_05/moment_of_inertia.webm", title: "Moment of Inertia" },
  "torque basics": { file: "/animations/physics/phy_05/moment_of_inertia.webm", title: "Moment of Inertia" },
  "moment of inertia simple": { file: "/animations/physics/phy_05/moment_of_inertia.webm", title: "Moment of Inertia" },
  "moment of inertia composite": { file: "/animations/physics/phy_05/parallel_axis.webm", title: "Parallel Axis Theorem" },
  "angular momentum": { file: "/animations/physics/phy_05/angular_momentum.webm", title: "Angular Momentum" },
  "conservation of angular momentum": { file: "/animations/physics/phy_05/angular_momentum.webm", title: "Angular Momentum" },
  "rolling without slipping": { file: "/animations/physics/phy_05/rolling_motion.webm", title: "Rolling Motion" },

  // phy_06 - Gravitation
  "gravitational force": { file: "/animations/physics/phy_06/gravitational_force.webm", title: "Gravitational Force" },
  "gravitational field": { file: "/animations/physics/phy_06/gravitational_force.webm", title: "Gravitational Force" },
  "gravitational potential": { file: "/animations/physics/phy_06/gravitational_potential.webm", title: "Gravitational Potential" },
  "escape velocity": { file: "/animations/physics/phy_06/escape_velocity.webm", title: "Escape Velocity" },
  "orbital velocity": { file: "/animations/physics/phy_06/orbital_velocity.webm", title: "Orbital Velocity" },
  "Kepler laws": { file: "/animations/physics/phy_06/kepler_third_law.webm", title: "Kepler's Third Law" },

  // phy_07 - Properties of Matter
  "stress strain": { file: "/animations/physics/phy_07/stress_strain.webm", title: "Stress-Strain Curve" },
  "Young's modulus": { file: "/animations/physics/phy_07/stress_strain.webm", title: "Stress-Strain Curve" },
  "pressure in fluids": { file: "/animations/physics/phy_07/fluid_continuity.webm", title: "Fluid Continuity" },
  "Archimedes principle": { file: "/animations/physics/phy_07/fluid_continuity.webm", title: "Fluid Continuity" },
  "Bernoulli equation": { file: "/animations/physics/phy_07/bernoulli_equation.webm", title: "Bernoulli's Equation" },

  // phy_08 - Thermodynamics
  "thermal expansion": { file: "/animations/physics/phy_08/ideal_gas_law.webm", title: "Ideal Gas Law" },
  "ideal gas law": { file: "/animations/physics/phy_08/ideal_gas_law.webm", title: "Ideal Gas Law" },
  "kinetic theory basics": { file: "/animations/physics/phy_08/ideal_gas_law.webm", title: "Ideal Gas Law" },
  "first law of thermodynamics": { file: "/animations/physics/phy_08/first_law_thermo.webm", title: "First Law of Thermodynamics" },
  "second law": { file: "/animations/physics/phy_08/carnot_cycle.webm", title: "Carnot Cycle" },
  "Carnot cycle": { file: "/animations/physics/phy_08/carnot_cycle.webm", title: "Carnot Cycle" },
  "heat transfer modes": { file: "/animations/physics/phy_08/isothermal_work.webm", title: "Isothermal Work" },

  // phy_09 - Oscillations and Waves
  "SHM basics": { file: "/animations/physics/phy_09/shm_equation.webm", title: "SHM Equation" },
  "SHM energy": { file: "/animations/physics/phy_09/shm_period.webm", title: "SHM Period" },
  "spring mass system": { file: "/animations/physics/phy_09/shm_period.webm", title: "SHM Period" },
  "pendulum": { file: "/animations/physics/phy_09/shm_period.webm", title: "SHM Period" },
  "wave equation": { file: "/animations/physics/phy_09/wave_velocity.webm", title: "Wave Velocity" },
  "superposition": { file: "/animations/physics/phy_09/superposition.webm", title: "Superposition" },
  "beats": { file: "/animations/physics/phy_09/superposition.webm", title: "Superposition" },
  "Doppler effect": { file: "/animations/physics/phy_09/doppler_effect.webm", title: "Doppler Effect" },

  // phy_10 - Electrostatics
  "Coulomb's law": { file: "/animations/physics/phy_10/coulombs_law.webm", title: "Coulomb's Law" },
  "electric field basics": { file: "/animations/physics/phy_10/electric_field.webm", title: "Electric Field" },
  "electric field lines": { file: "/animations/physics/phy_10/electric_field.webm", title: "Electric Field" },
  "Gauss law basics": { file: "/animations/physics/phy_10/gauss_law.webm", title: "Gauss's Law" },
  "Gauss law applications": { file: "/animations/physics/phy_10/gauss_law.webm", title: "Gauss's Law" },
  "capacitance": { file: "/animations/physics/phy_10/capacitor_charging.webm", title: "Capacitor Charging" },

  // phy_11 - Current Electricity
  "Ohm's law": { file: "/animations/physics/phy_11/ohms_law.webm", title: "Ohm's Law" },
  "resistance combinations": { file: "/animations/physics/phy_11/parallel_resistance.webm", title: "Parallel Resistance" },
  "RC circuit basics": { file: "/animations/physics/phy_11/rc_discharge.webm", title: "RC Discharge" },

  // phy_12 - Magnetic Effects
  "magnetic field due to straight wire": { file: "/animations/physics/phy_12/biot_savart.webm", title: "Biot-Savart Law" },
  "Biot-Savart law": { file: "/animations/physics/phy_12/biot_savart.webm", title: "Biot-Savart Law" },
  "force on moving charge": { file: "/animations/physics/phy_12/lorentz_force.webm", title: "Lorentz Force" },
  "torque on current loop": { file: "/animations/physics/phy_12/magnetic_dipole.webm", title: "Magnetic Dipole" },

  // phy_13 - Electromagnetic Induction
  "magnetic flux": { file: "/animations/physics/phy_13/magnetic_flux.webm", title: "Magnetic Flux" },
  "Faraday's law": { file: "/animations/physics/phy_13/faraday_law.webm", title: "Faraday's Law" },
  "self inductance": { file: "/animations/physics/phy_13/lcr_oscillation.webm", title: "LCR Oscillation" },
  "LCR circuit": { file: "/animations/physics/phy_13/lcr_oscillation.webm", title: "LCR Oscillation" },
  "resonance": { file: "/animations/physics/phy_13/resonant_frequency.webm", title: "Resonant Frequency" },

  // phy_14 - Optics
  "reflection": { file: "/animations/physics/phy_14/mirror_formula.webm", title: "Mirror Formula" },
  "refraction": { file: "/animations/physics/phy_14/snells_law.webm", title: "Snell's Law" },
  "lens formula": { file: "/animations/physics/phy_14/lens_formula.webm", title: "Lens Formula" },
  "interference": { file: "/animations/physics/phy_14/interference_fringes.webm", title: "Interference Fringes" },

  // phy_15 - Modern Physics
  "photoelectric effect": { file: "/animations/physics/phy_15/photoelectric_effect.webm", title: "Photoelectric Effect" },
  "Bohr model": { file: "/animations/physics/phy_15/bohr_orbits.webm", title: "Bohr Orbits" },
  "radioactive decay": { file: "/animations/physics/phy_15/radioactive_decay.webm", title: "Radioactive Decay" },

  // ═══════════════════════════════════════════════════════════
  // MATH
  // ═══════════════════════════════════════════════════════════

  // math_01 - Sets
  "De Morgan's Laws": { file: "/animations/maths/math_01/venn_diagram.webm", title: "Venn Diagram" },

  // math_02 - Complex Numbers
  "Modulus of Complex Number": { file: "/animations/maths/math_02/argand_plane.webm", title: "Argand Plane" },
  "Euler's Formula": { file: "/animations/maths/math_02/euler_formula.webm", title: "Euler's Formula" },
  "De Moivre's Theorem": { file: "/animations/maths/math_02/de_moivre.webm", title: "De Moivre's Theorem" },
  "Cube Roots of Unity": { file: "/animations/maths/math_02/roots_of_unity.webm", title: "Roots of Unity" },

  // math_03 - Quadratic Equations
  "Quadratic Formula": { file: "/animations/maths/math_03/quadratic_formula.webm", title: "Quadratic Formula" },
  "Discriminant": { file: "/animations/maths/math_03/discriminant_visual.webm", title: "Discriminant Visual" },
  "Vertex of Parabola": { file: "/animations/maths/math_03/vertex_form.webm", title: "Vertex Form" },

  // math_04 - Sequences
  "AP n-th Term": { file: "/animations/maths/math_04/ap_sequence.webm", title: "AP Sequence" },
  "AP Sum": { file: "/animations/maths/math_04/ap_sequence.webm", title: "AP Sequence" },
  "GP n-th Term": { file: "/animations/maths/math_04/gp_sequence.webm", title: "GP Sequence" },
  "Infinite GP Sum": { file: "/animations/maths/math_04/gp_sequence.webm", title: "GP Sequence" },
  "AM-GM-HM": { file: "/animations/maths/math_04/amgm_inequality.webm", title: "AM-GM Inequality" },

  // math_05 - P&C
  "Binomial Expansion": { file: "/animations/maths/math_05/binomial_expansion.webm", title: "Binomial Expansion" },

  // math_06 - Matrices
  "Determinant": { file: "/animations/maths/math_06/determinant_2x2.webm", title: "Determinant" },
  "Matrix Inverse": { file: "/animations/maths/math_06/linear_transformation.webm", title: "Linear Transformation" },

  // math_07 - Limits
  "Limit": { file: "/animations/maths/math_07/limit_approach.webm", title: "Limit Approach" },
  "Sinc Limit": { file: "/animations/maths/math_07/sinc_limit.webm", title: "Sinc Limit" },
  "Derivative": { file: "/animations/maths/math_07/derivative_as_limit.webm", title: "Derivative as Limit" },

  // math_08 - Applications of Derivatives
  "Tangent": { file: "/animations/maths/math_08/tangent_line.webm", title: "Tangent Line" },
  "Normal": { file: "/animations/maths/math_08/normal_line.webm", title: "Normal Line" },
  "MVT": { file: "/animations/maths/math_08/mean_value_theorem.webm", title: "Mean Value Theorem" },
  "Extrema": { file: "/animations/maths/math_08/extrema.webm", title: "Extrema" },

  // math_09 - Integrals
  "Integration": { file: "/animations/maths/math_09/area_under_curve.webm", title: "Area Under Curve" },
  "Integration by Parts": { file: "/animations/maths/math_09/integration_by_parts.webm", title: "Integration by Parts" },
  "King's Rule": { file: "/animations/maths/math_09/king_rule.webm", title: "King's Rule" },

  // math_10 - Differential Equations
  "Separable DE": { file: "/animations/maths/math_10/separable_de.webm", title: "Separable DE" },
  "Integrating Factor": { file: "/animations/maths/math_10/integrating_factor.webm", title: "Integrating Factor" },

  // math_11 - Coordinate Geometry
  "Circle": { file: "/animations/maths/math_11/circle_equation.webm", title: "Circle Equation" },
  "Parabola": { file: "/animations/maths/math_11/parabola_conic.webm", title: "Parabola" },
  "Ellipse": { file: "/animations/maths/math_11/ellipse_conic.webm", title: "Ellipse" },
  "Distance": { file: "/animations/maths/math_11/distance_point_line.webm", title: "Distance" },

  // math_12 - Vectors
  "Dot Product": { file: "/animations/maths/math_12/dot_product.webm", title: "Dot Product" },
  "Cross Product": { file: "/animations/maths/math_12/cross_product.webm", title: "Cross Product" },
  "Projection": { file: "/animations/maths/math_12/vector_projection.webm", title: "Vector Projection" },
  "Triple Product": { file: "/animations/maths/math_12/triple_product.webm", title: "Triple Product" },

  // math_13 - 3D Geometry
  "Plane": { file: "/animations/maths/math_13/plane_equation.webm", title: "Plane Equation" },
  "Skew Lines": { file: "/animations/maths/math_13/skew_lines.webm", title: "Skew Lines" },

  // math_14 - Probability
  "Bayes": { file: "/animations/maths/math_14/bayes_tree.webm", title: "Bayes Tree" },
  "Binomial Distribution": { file: "/animations/maths/math_14/binomial_dist.webm", title: "Binomial Distribution" },
  "Conditional Probability": { file: "/animations/maths/math_14/conditional_prob.webm", title: "Conditional Probability" },

  // math_15 - Trigonometry
  "Unit Circle": { file: "/animations/maths/math_15/unit_circle.webm", title: "Unit Circle" },
  "Double Angle": { file: "/animations/maths/math_15/double_angle.webm", title: "Double Angle" },
  "Sum to Product": { file: "/animations/maths/math_15/sum_to_product.webm", title: "Sum to Product" },
  "Sine Rule": { file: "/animations/maths/math_15/sine_rule.webm", title: "Sine Rule" },

  // ═══════════════════════════════════════════════════════════
  // CHEMISTRY
  // ═══════════════════════════════════════════════════════════

  // chem_02 - Atomic Structure
  "Bohr orbits": { file: "/animations/chemistry/chem_02/bohr_orbits.webm", title: "Bohr Orbits" },
  "Rydberg formula": { file: "/animations/chemistry/chem_02/rydberg_formula.webm", title: "Rydberg Formula" },
  "Heisenberg": { file: "/animations/chemistry/chem_02/heisenberg_uncertainty.webm", title: "Heisenberg Uncertainty" },
  "Orbitals": { file: "/animations/chemistry/chem_02/orbital_shapes.webm", title: "Orbital Shapes" },

  // chem_03 - Chemical Bonding
  "VSEPR": { file: "/animations/chemistry/chem_03/vsepr_geometry.webm", title: "VSEPR Geometry" },
  "Molecular Orbital": { file: "/animations/chemistry/chem_03/molecular_orbital.webm", title: "Molecular Orbital" },
  "Dipole": { file: "/animations/chemistry/chem_03/dipole_moment.webm", title: "Dipole Moment" },

  // chem_04 - Thermodynamics
  "Hess's Law": { file: "/animations/chemistry/chem_04/hess_law_cycle.webm", title: "Hess's Law" },
  "Enthalpy": { file: "/animations/chemistry/chem_04/enthalpy_levels.webm", title: "Enthalpy Levels" },
  "Gibbs": { file: "/animations/chemistry/chem_04/gibbs_energy.webm", title: "Gibbs Energy" },

  // chem_05 - Equilibrium
  "Le Chatelier": { file: "/animations/chemistry/chem_05/le_chatelier_principle.webm", title: "Le Chatelier" },
  "pH Curve": { file: "/animations/chemistry/chem_05/ph_curve.webm", title: "pH Curve" },
  "Equilibrium": { file: "/animations/chemistry/chem_05/equilibrium_constant.webm", title: "Equilibrium Constant" },

  // chem_06 - Electrochemistry
  "Galvanic Cell": { file: "/animations/chemistry/chem_06/galvanic_cell.webm", title: "Galvanic Cell" },
  "Nernst": { file: "/animations/chemistry/chem_06/nernst_equation.webm", title: "Nernst Equation" },
  "Electrolysis": { file: "/animations/chemistry/chem_06/electrolysis.webm", title: "Electrolysis" },

  // chem_07 - Kinetics
  "First Order": { file: "/animations/chemistry/chem_07/first_order_kinetics.webm", title: "First Order Kinetics" },
  "Half Life": { file: "/animations/chemistry/chem_07/half_life.webm", title: "Half Life" },
  "Arrhenius": { file: "/animations/chemistry/chem_07/arrhenius_plot.webm", title: "Arrhenius Plot" },
  "Rate Laws": { file: "/animations/chemistry/chem_07/rate_laws.webm", title: "Rate Laws" },

  // chem_08 - Coordination Chemistry
  "Crystal Field": { file: "/animations/chemistry/chem_08/crystal_field_splitting.webm", title: "Crystal Field Splitting" },
  "Octahedral": { file: "/animations/chemistry/chem_08/octahedral_geometry.webm", title: "Octahedral Geometry" },
  "Magnetic Moment": { file: "/animations/chemistry/chem_08/magnetic_moment.webm", title: "Magnetic Moment" },
};

// Helper to find animation for a concept
export function findAnimation(concept: string) {
  if (!concept) return null;
  const lower = concept.toLowerCase();
  for (const [key, value] of Object.entries(ANIMATIONS)) {
    if (lower.includes(key.toLowerCase()) || key.toLowerCase().includes(lower)) {
      return value;
    }
  }
  return null;
}
